"""Demo mode - Test system without AWS."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

print("🎯 Swiss Medical Triage System - Demo Mode")
print("=" * 60)
print()
print("✅ SERVICIOS ACTIVOS:")
print()
print("1. 🌐 Streamlit UI")
print("   URL: http://localhost:8501")
print("   Estado: CORRIENDO")
print()
print("2. ⚡ FastAPI REST API")
print("   URL: http://localhost:8000")
print("   Docs: http://localhost:8000/docs")
print("   Estado: CORRIENDO")
print()
print("=" * 60)
print()
print("📋 FUNCIONALIDADES DISPONIBLES (sin AWS):")
print()
print("✅ Interfaz de usuario completa")
print("✅ Navegación entre páginas")
print("✅ Formularios de entrada")
print("✅ Visualización de datos")
print()
print("⚠️  REQUIERE AWS PARA:")
print()
print("❌ Crear/consultar pacientes (DynamoDB)")
print("❌ Evaluación de triaje con IA (Bedrock)")
print("❌ Almacenar historial (DynamoDB)")
print()
print("=" * 60)
print()
print("🔧 PARA HABILITAR FUNCIONALIDAD COMPLETA:")
print()
print("1. Configurar credenciales AWS en .env")
print("2. Habilitar AWS Bedrock (Claude 3 Sonnet)")
print("3. Crear tablas DynamoDB")
print()
print("Ejecuta: python scripts/setup_aws_guide.py")
print()
print("=" * 60)
print()
print("🚀 ACCEDE AHORA:")
print()
print("   Abre tu navegador en: http://localhost:8501")
print()
